name: athena
channels:
  - defaults
dependencies:
  - certifi=2019.3.9=py36_0
  - pip=19.0.3=py36_0
  - python=3.6.8=h9f7ef89_7
  - setuptools=40.8.0=py36_0
  - sqlite=3.27.2=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.33.1=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - blis==0.2.4
    - boto==2.49.0
    - boto3==1.9.125
    - botocore==1.12.125
    - bz2file==0.98
    - chardet==3.0.4
    - colorama==0.4.1
    - cycler==0.10.0
    - cymem==2.0.2
    - decorator==4.4.0
    - defusedxml==0.5.0
    - docutils==0.14
    - entrypoints==0.3
    - gensim==3.7.1
    - idna==2.8
    - ipykernel==5.1.0
    - ipython==7.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10
    - jmespath==0.9.4
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - markupsafe==1.1.1
    - matplotlib==3.0.3
    - mistune==0.8.4
    - murmurhash==1.0.2
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - notebook==5.7.7
    - numpy==1.16.2
    - pandas==0.24.2
    - pandocfilters==1.4.2
    - parso==0.3.4
    - pickleshare==0.7.5
    - plac==0.9.6
    - praw==6.1.1
    - prawcore==1.0.1
    - preshed==2.0.1
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - pygments==2.3.1
    - pyparsing==2.3.1
    - pyrsistent==0.14.11
    - python-dateutil==2.8.0
    - pytz==2018.9
    - pywinpty==0.5.5
    - pyzmq==18.0.1
    - qtconsole==4.4.3
    - requests==2.21.0
    - s3transfer==0.2.0
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - seaborn==0.9.0
    - send2trash==1.5.0
    - six==1.12.0
    - smart-open==1.8.0
    - spacy==2.1.3
    - srsly==0.0.5
    - terminado==0.8.2
    - testpath==0.4.2
    - thinc==7.0.4
    - tornado==6.0.2
    - tqdm==4.31.1
    - traitlets==4.3.2
    - update-checker==0.16
    - urllib3==1.24.1
    - wasabi==0.2.1
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - widgetsnbextension==3.4.2
    - xlrd==1.2.0
prefix: C:\Users\jared.wilber\AppData\Local\Continuum\anaconda3\envs\athena

